version: '3.8'
services:
  api:
    build: .
    container_name: rag_api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - vectordb
      - db
  vectordb:
    image: chromadb/chroma:latest
    container_name: chroma_db
    ports:
      - "8000:8000"
  db:
    image: postgres:15
    container_name: rag_postgres
    environment:
      POSTGRES_USER: raguser
      POSTGRES_PASSWORD: ragpass
      POSTGRES_DB: ragdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
